const snoowrap = require("snoowrap");

// Replace these with your Reddit app credentials
const r = new snoowrap({
  userAgent: process.env.REDDIT_USER_AGENT,
  clientId: process.env.REDDIT_CLIENT_ID,
  clientSecret: process.env.REDDIT_CLIENT_SECRET,
  username: process.env.REDDIT_USERNAME,
  password: process.env.REDDIT_PASSWORD,
});

const subreddits = [
  "AIQuestions",
  "APIBuilders",
  "API_development",
  "AppDesign",
  "AppIdeas",
  "Artificial",
  "ArtificialIntelligence",
  "AskAcademia",
  "AskAnthropology",
  "AskComputers",
  "AskCulinary",
  "AskDocs",
  "AskEngineers",
  "AskHR",
  "AskManagement",
  "AskMath",
  "AskMen",
  "AskProgramming",
  "AskReddit",
  "AskScience",
  "AskSocialScience",
  "AskStatistics",
  "AskTech",
  "AskTechnology",
  "AskTeens",
  "AskWomen",
  "Backend",
  "Biology",
  "buildapc",
  "ChangeMyView",
  "ChatGPT",
  "Chemistry",
  "ClientProblems",
  "College",
  "computerscience",
  "Consulting",
  "ConsultingCanada",
  "ConsultingUK",
  "ContentCreators",
  "coding",
  "cordcutters",
  "CreatorAdvice",
  "cscareerquestions",
  "CyberSecurity",
  "dataengineering",
  "DataEngineeringJobs",
  "DataHoarder",
  "DataScience",
  "DecidingToBeBetter",
  "design",
  "DesignCritiques",
  "DesignJobs",
  "devops",
  "devopsjobs",
  "digitalnomad",
  "Economics",
  "ElectricalEngineering",
  "electronics",
  "engineering",
  "Entrepreneur",
  "EntrepreneurIdeas",
  "EntrepreneurRideAlong",
  "ExplainLikeImFive",
  "Fixit",
  "Fullstack",
  "Gadgets",
  "GetDisciplined",
  "GetMotivated",
  "GradSchool",
  "graphic_design",
  "growthhacking",
  "help",
  "homeautomation",
  "HowTo",
  "IndieBiz",
  "InfraSec",
  "Instagram",
  "InternetIsBeautiful",
  "ITCareerQuestions",
  "ITSupport",
  "iOS",
  "Java",
  "jobsearch",
  "jobs",
  "LearnComputerScience",
  "LearnJava",
  "LearnJavaScript",
  "LearnMath",
  "LearnNewThings",
  "LearnPython",
  "LearnRust",
  "LearnUselessTalents",
  "LearnUX",
  "learnprogramming",
  "Lightbulb",
  "LifeProTips",
  "LLMDevelopers",
  "MachineLearning",
  "MachineLearningProblems",
  "math",
  "MechanicalEngineering",
  "MicroSaaS",
  "Microstartups",
  "MobileApps",
  "Network",
  "networking",
  "NewTubers",
  "NextJS",
  "Node",
  "NoStupidQuestions",
  "Notion",
  "NotionHQ",
  "OpenAI_Developers",
  "openai",
  "OpenSourceIdeas",
  "opensource",
  "PersonalFinance",
  "Physics",
  "ProductManagement",
  "ProductManagementJobs",
  "Productivity",
  "ProductivityApps",
  "programming",
  "promptengineering",
  "reactjs",
  "remoteWork",
  "ReverseEngineering",
  "SaaS",
  "SaaSideas",
  "saasdevelopment",
  "SaaSDevelopment",
  "Science",
  "Showerthoughts",
  "SideProject",
  "SideProjectIdeas",
  "smallbusiness",
  "SmartHome",
  "SocialMedia",
  "SoftwareDesign",
  "SoftwareEngineering",
  "SomebodyMakeThis",
  "Startups",
  "Startup_Ideas",
  "StartupSuccess",
  "Student",
  "StudyTips",
  "sysadmin",
  "systemdesign",
  "technology",
  "TechNews",
  "TechProblems",
  "TechSupport",
  "TechSupportAdvice",
  "TooAfraidToAsk",
  "trends",
  "TrueOffMyChest",
  "typescript",
  "UI_Design",
  "UI_UX_Critique",
  "UserExperience",
  "webdev",
  "webdevjobs",
  "webhosting",
  "WorkFromHome",
  "WorkOnline",
  "YouTubers",

  // Extra similar content
  "ArtificialIntelligenceArt",
  "AIArt",
  "AIWriting",
  "AIprogramming",
  "Blockchain",
  "Crypto",
  "Web3",
  "FinTech",
  "StartUpMarketing",
  "SideHustle",
  "ProductHunt",
  "AppLaunch",
  "IndieDev",
  "MobileDev",
  "ReactNative",
  "NodeJSProjects",
  "FrontendDev",
  "BackendDev",
  "FullstackDev",
  "DataVisualization",
  "OpenSourceProjects",
  "TechStartups",
  "ProgrammingHumor",
  "AIResearch",
  "DeepLearning",
  "MachineLearningJobs",
];

// Utility sleep function
function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

// Check which subreddits exist
async function checkSubreddits(list) {
  const validSubreddits = [];

  for (const sub of list) {
    try {
      const subreddit = await r.getSubreddit(sub).fetch();
      if (subreddit) {
        console.log(`✅ Found subreddit: ${sub}`);
        validSubreddits.push(sub);
      }
      await sleep(500); // small delay between requests
    } catch (err) {
      if (err.statusCode === 404) {
        console.log(`❌ Subreddit not found: ${sub}`);
      } else {
        console.error(`Error fetching ${sub}:`, err.message || err);
        await sleep(2000); // wait before retrying
      }
    }
  }

  console.log("\nValid subreddits:", validSubreddits.join(","));
  return validSubreddits;
}

// Run the function
checkSubreddits(subreddits).then((result) => console.log("Done:", result));
